create or replace table comorbidities as 
with aids_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/aids_bl.csv',header=true, all_varchar=TRUE)),
ami_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/ami_bl.csv',header=true, all_varchar=TRUE)),
chf_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/chf_bl.csv',header=true, all_varchar=TRUE)),
ckd_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/ckd_bl.csv',header=true, all_varchar=TRUE)),
copd_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/copd_bl.csv',header=true, all_varchar=TRUE)),
ctp_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/ctp_bl.csv',header=true, all_varchar=TRUE)),
cvd_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/cvd_bl.csv',header=true, all_varchar=TRUE)),
dementia_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/dementia_bl.csv',header=true, all_varchar=TRUE)),
hemiplegia_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/hemiplegia_bl.csv',header=true, all_varchar=TRUE)),
leuk_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/leuk_bl.csv',header=true, all_varchar=TRUE)),
lymph_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/lymph_bl.csv',header=true, all_varchar=TRUE)),
mildliver_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/mildliver_bl.csv',header=true, all_varchar=TRUE)),
mtx_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/mtx_bl.csv',header=true, all_varchar=TRUE)),
orgdiab_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/orgdiab_bl.csv',header=true, all_varchar=TRUE)),
peptic_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/peptic_bl.csv',header=true, all_varchar=TRUE)),
pvd_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/pvd_bl.csv',header=true, all_varchar=TRUE)),
severeliver_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/severeliver_bl.csv',header=true, all_varchar=TRUE)),
tumor_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/tumor_bl.csv',header=true, all_varchar=TRUE)),
uncdiab_bl_df as (select array_agg(code_clean) as code_clean_list from read_csv('aux_files/comorbidities/uncdiab_bl.csv',header=true, all_varchar=TRUE)),
episodios as (select patient_id,cnh_cd,episode_id,admission_dt, list_where([d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20],
									list_transform([poad1,poad2,poad3,poad4,poad5,poad6,poad7,poad8,poad9,poad10,poad11,poad12,poad13,poad14,poad15,poad16,poad17,poad18,poad19,poad20], x -> (
									case when x in ('S','I','E') then true else false end))) as diagnosticos from episode_view)
select patient_id,cnh_cd,episode_id,admission_dt, 
diagnosticos && b.code_clean_list as aids_bl , 
diagnosticos && c.code_clean_list as ami_bl,
diagnosticos && d.code_clean_list as chf_bl,
diagnosticos && e.code_clean_list as ckd_bl,
diagnosticos && f.code_clean_list as copd_bl,
diagnosticos && g.code_clean_list as ctp_bl,
diagnosticos && h.code_clean_list as cvd_bl,
diagnosticos && i.code_clean_list as dementia_bl,
diagnosticos && j.code_clean_list as hemiplegia_bl,
diagnosticos && k.code_clean_list as leuk_bl,
diagnosticos && l.code_clean_list as lymph_bl,
diagnosticos && m.code_clean_list as mildliver_bl,
diagnosticos && n.code_clean_list as mtx_bl,
diagnosticos && o.code_clean_list as orgdiab_bl,
diagnosticos && p.code_clean_list as peptic_bl,
diagnosticos && q.code_clean_list as pvd_bl,
diagnosticos && r.code_clean_list as severeliver_bl,
diagnosticos && s.code_clean_list as tumor_bl,
diagnosticos && t.code_clean_list as uncdiab_bl
from episodios a , aids_bl_df b, ami_bl_df c, chf_bl_df d, ckd_bl_df e, copd_bl_df f, ctp_bl_df g, cvd_bl_df h,
dementia_bl_df i,hemiplegia_bl_df j,leuk_bl_df k,lymph_bl_df l,mildliver_bl_df m,mtx_bl_df n , orgdiab_bl_df o ,
peptic_bl_df p , pvd_bl_df q, severeliver_bl_df r, tumor_bl_df s, uncdiab_bl_df t 